= Learn/Teach/Repeat

Presentation content in *_bold italics_* and learnings in `monospace`

= JDBC
Intro
JDBC is an api which defines how client may access the database. Provides methods to query, update data in database.It uses JDBC drivers to connect with the database. Current version 4.2 MR release in Java 1.8.

`api: application program interface is code that allows two applications to communicate with each other. It tells developers how to make requests/calls to OS/other applications. Typically APIs are released for third-party developement as part of SDKs`

The JDBC classes are contained in the Java package, java.sql and javax.sql

Architecture
JDBC API - Program to JDBC Manager connenction - which we'll be using to code
JDBC Driver API - JDBC Manager to driver connection - specific for database vendors like Oracle, MySql etc

JDBC Driver - implements JDBC interfaces (comes with standard Java) targetting a particular database
*JDBC-ODBC Bridge driver
*Native Api driver
*Network protocol driver

= AWS
Elastic Computing - avoid overprovisioning and scale up for the needs

Global Infrastructure
region - geographical area us-east, es-west
availability zone - data center, within a particular region
edge locations - doesn't have aws resources, but have some services eg: dns, cloudfront

Shared Security Responsibility
AWS responsibility - host, storage, network, datacenter security
Our Reponsibility - AWS account security

Identity and Access Managament IAM
-user and service management
-control access to AWS resources
-MFA
API access

Elastic Compute Cloud EC2
-scalable plaforms for VMs
-windows/linux instances
-based of AMI Amazon Machine Image - template/configuration to deploy a VM
-ECU - measure the CPU usage. 1ECU - 1.2GHz 2007 Intel Opteron or 2007 Xeon. moved to vCPU
-instance types based on workload - micro instances, general purpose, compute optimized, GPU instances, memory optimized, storage optimized