= First Blog Post Using AsciiDoc in HubPress

I'd be following http://asciidoctor.org/docs/asciidoc-writers-guide/#writing-in-asciidoc to get started with AsciiDoc. Its similar to Markdown, which should help this journey.

//Start

This line,
and this line are seperate lines! That's my first learning: AsciiDoc combines adjacent lines. So to preserve line breaks, use plus sign(+) or hardbreaks attribute(which have two variants: [%hardbreaks] and :hardbreaks: the later sets line break preserve for the entire doc,which i can't show here). See the examples below.

Using plus(+) +
This line, +
and this line are seperate lines!

Voila! Line Breaks!

Using hardbreaks
[%hardbreaks]
This line,
and this line are seperate lines!
[hardbreaks]

So using hardbreaks attribute, you should put [%hardbreaks] in the line before (and in seperate line) you need to preserve line breaks and put [hardbreaks] where you need to end the behaviour.


Admonitions http://asciidoctor.org/docs/asciidoc-writers-guide/#admonitions

NOTE: hardbreaks attribute seems to be adding a seperate break line by itself. + sign should be put after a space.

Quoted text +
bold: * * enclose phrase/letter in *_asteriks_*: *bold* +
italic: _ _ enclose phrase/letter in *_underscore_*: _italic_ +
monospace font: ` ` enclose phrase/letter in *_tilde_*: `monospace` +
